-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.active_carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  abandoned_at timestamp with time zone,
  CONSTRAINT active_carts_pkey PRIMARY KEY (id),
  CONSTRAINT active_carts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT active_carts_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_messages_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  customer_id uuid,
  message_type text NOT NULL CHECK (message_type = ANY (ARRAY['cart_recovery'::text, 'win_back'::text, 'loyalty_nudge'::text, 'birthday'::text, 'after_order'::text, 'new_item_launch'::text, 'quiet_day'::text, 'milestone'::text])),
  channel text NOT NULL DEFAULT 'email'::text CHECK (channel = ANY (ARRAY['email'::text, 'push'::text])),
  reference_id text,
  subject text,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_messages_log_pkey PRIMARY KEY (id),
  CONSTRAINT ai_messages_log_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT ai_messages_log_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.campaign_automation_settings (
  restaurant_id uuid NOT NULL,
  birthday_enabled boolean NOT NULL DEFAULT true,
  after_order_enabled boolean NOT NULL DEFAULT true,
  quiet_day_enabled boolean NOT NULL DEFAULT true,
  milestone_enabled boolean NOT NULL DEFAULT true,
  new_item_enabled boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaign_automation_settings_pkey PRIMARY KEY (restaurant_id),
  CONSTRAINT campaign_automation_settings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.campaign_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'clicked'::text, 'converted'::text])),
  click_token uuid NOT NULL DEFAULT gen_random_uuid(),
  subject text,
  sent_at timestamp with time zone,
  clicked_at timestamp with time zone,
  converted_at timestamp with time zone,
  order_id uuid,
  revenue_attributed numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaign_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_contacts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_contacts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT campaign_contacts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT campaign_contacts_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  campaign_type text NOT NULL CHECK (campaign_type = ANY (ARRAY['birthday'::text, 'after_order'::text, 'new_item_launch'::text, 'quiet_day'::text, 'milestone'::text, 'win_back'::text, 'cart_recovery'::text, 'loyalty_nudge'::text])),
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text])),
  sent_count integer NOT NULL DEFAULT 0,
  click_count integer NOT NULL DEFAULT 0,
  order_count integer NOT NULL DEFAULT 0,
  revenue_attributed numeric NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  available_order_types ARRAY,
  happy_hour_enabled boolean NOT NULL DEFAULT false,
  happy_hour_start time without time zone,
  happy_hour_end time without time zone,
  happy_hour_days ARRAY,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.customer_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  label text NOT NULL DEFAULT 'Home'::text,
  address_line_1 text NOT NULL,
  address_line_2 text,
  city text NOT NULL,
  state text NOT NULL,
  zip text NOT NULL,
  country text NOT NULL DEFAULT 'US'::text,
  latitude numeric,
  longitude numeric,
  is_default boolean NOT NULL DEFAULT false,
  delivery_zone_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT customer_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_addresses_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.customer_dietary_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  flag_type text NOT NULL CHECK (flag_type = ANY (ARRAY['vegetarian'::text, 'vegan'::text, 'gluten_free'::text, 'halal'::text, 'kosher'::text, 'nut_allergy'::text, 'dairy_free'::text, 'shellfish_allergy'::text, 'other'::text])),
  source text NOT NULL DEFAULT 'self_reported'::text CHECK (source = ANY (ARRAY['self_reported'::text, 'inferred_from_orders'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_dietary_flags_pkey PRIMARY KEY (id),
  CONSTRAINT customer_dietary_flags_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_dietary_flags_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.customer_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['order_placed'::text, 'order_cancelled'::text, 'order_refunded'::text, 'reservation_made'::text, 'reservation_cancelled'::text, 'cart_abandoned'::text, 'item_viewed'::text, 'promo_redeemed'::text, 'promo_ignored'::text, 'review_submitted'::text, 'support_ticket_opened'::text, 'loyalty_points_earned'::text, 'loyalty_points_redeemed'::text, 'email_opened'::text, 'email_clicked'::text, 'sms_opened'::text, 'app_session_started'::text, 'login'::text, 'logout'::text])),
  event_at timestamp with time zone NOT NULL,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  session_id text,
  device_type text NOT NULL DEFAULT 'desktop_web'::text CHECK (device_type = ANY (ARRAY['mobile_web'::text, 'desktop_web'::text, 'ios_app'::text, 'android_app'::text])),
  source_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT customer_events_pkey PRIMARY KEY (id),
  CONSTRAINT customer_events_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_events_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.customer_profiles (
  id uuid NOT NULL,
  display_name text NOT NULL,
  phone text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT customer_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_segment_members (
  segment_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  added_at timestamp with time zone NOT NULL DEFAULT now(),
  added_by text NOT NULL DEFAULT 'manual'::text,
  CONSTRAINT customer_segment_members_pkey PRIMARY KEY (segment_id, customer_id),
  CONSTRAINT customer_segment_members_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.customer_segments(id),
  CONSTRAINT customer_segment_members_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_segment_members_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.customer_segments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  color text NOT NULL DEFAULT '#6B7280'::text,
  is_system boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_segments_pkey PRIMARY KEY (id),
  CONSTRAINT customer_segments_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT customer_segments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  first_name text,
  last_name text,
  birthday date,
  anniversary date,
  preferred_contact_method text NOT NULL DEFAULT 'none'::text CHECK (preferred_contact_method = ANY (ARRAY['email'::text, 'sms'::text, 'push'::text, 'none'::text])),
  marketing_opt_in boolean NOT NULL DEFAULT false,
  marketing_opt_in_at timestamp with time zone,
  acquisition_source text NOT NULL DEFAULT 'organic'::text CHECK (acquisition_source = ANY (ARRAY['organic'::text, 'google_ad'::text, 'instagram_ad'::text, 'facebook_ad'::text, 'referral'::text, 'qr_code'::text, 'walk_in'::text, 'loyalty_signup'::text, 'other'::text])),
  acquisition_campaign_id text,
  acquisition_source_detail text,
  loyalty_points_balance integer NOT NULL DEFAULT 0,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  notes text,
  is_blocked boolean NOT NULL DEFAULT false,
  last_seen_at timestamp with time zone,
  auth_user_id uuid,
  churn_risk_score double precision,
  ltv_predicted_90d numeric,
  segment_ai_label text,
  last_ai_scored_at timestamp with time zone,
  data_version integer NOT NULL DEFAULT 1,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT customers_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.device_push_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  expo_push_token text NOT NULL UNIQUE,
  platform text NOT NULL DEFAULT 'unknown'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT device_push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT device_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT device_push_tokens_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.loyalty_programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL UNIQUE,
  is_enabled boolean NOT NULL DEFAULT false,
  program_name text NOT NULL DEFAULT 'Rewards Club'::text,
  points_per_dollar integer NOT NULL DEFAULT 1,
  points_to_redeem integer NOT NULL DEFAULT 100,
  minimum_points_to_redeem integer NOT NULL DEFAULT 100,
  welcome_bonus_points integer NOT NULL DEFAULT 0,
  birthday_bonus_points integer NOT NULL DEFAULT 0,
  points_expiry_days integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT loyalty_programs_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_programs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  order_id uuid,
  points_delta integer NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['order_earn'::text, 'order_redeem'::text, 'order_refund'::text, 'welcome_bonus'::text, 'birthday_bonus'::text, 'manual_adjust'::text, 'expiry'::text])),
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT loyalty_transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT loyalty_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.menu_item_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  CONSTRAINT menu_item_tags_pkey PRIMARY KEY (id),
  CONSTRAINT menu_item_tags_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT menu_item_tags_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT menu_item_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  category_id uuid,
  subcategory_id uuid,
  name text NOT NULL,
  description text,
  price numeric NOT NULL DEFAULT 0,
  image_url text,
  is_available boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  available_order_types ARRAY,
  happy_hour_enabled boolean NOT NULL DEFAULT false,
  happy_hour_start time without time zone,
  happy_hour_end time without time zone,
  happy_hour_days ARRAY,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT menu_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT menu_items_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.subcategories(id)
);
CREATE TABLE public.option_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  name text NOT NULL,
  is_required boolean NOT NULL DEFAULT false,
  min_select integer NOT NULL DEFAULT 0,
  max_select integer NOT NULL DEFAULT 1,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT option_groups_pkey PRIMARY KEY (id),
  CONSTRAINT option_groups_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT option_groups_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  option_group_id uuid NOT NULL,
  name text NOT NULL,
  additional_price numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT options_pkey PRIMARY KEY (id),
  CONSTRAINT options_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT options_option_group_id_fkey FOREIGN KEY (option_group_id) REFERENCES public.option_groups(id)
);
CREATE TABLE public.order_item_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  order_item_id uuid NOT NULL,
  option_group_name_snapshot text NOT NULL,
  option_name_snapshot text NOT NULL,
  additional_price_snapshot numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT order_item_options_pkey PRIMARY KEY (id),
  CONSTRAINT order_item_options_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT order_item_options_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  order_id uuid NOT NULL,
  menu_item_id uuid,
  item_name_snapshot text NOT NULL,
  base_price_snapshot numeric NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  notes text,
  line_total numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  added_from_upsell boolean NOT NULL DEFAULT false,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  customer_id uuid,
  order_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'accepted'::text, 'preparing'::text, 'ready'::text, 'completed'::text, 'cancelled'::text])),
  order_type text NOT NULL DEFAULT 'pickup'::text CHECK (order_type = ANY (ARRAY['pickup'::text, 'dine_in'::text, 'delivery'::text])),
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  fee_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text NOT NULL DEFAULT ''::text,
  order_notes text,
  delivery_address text,
  delivery_instructions text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  customer_user_id uuid,
  loyalty_points_redeemed integer NOT NULL DEFAULT 0,
  loyalty_discount_amount numeric NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'stripe'::text])),
  stripe_payment_intent_id text,
  payment_status text NOT NULL DEFAULT 'unpaid'::text CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text, 'failed'::text, 'refunded'::text])),
  campaign_contact_id uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT orders_customer_user_id_fkey FOREIGN KEY (customer_user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_campaign_contact_id_fkey FOREIGN KEY (campaign_contact_id) REFERENCES public.campaign_contacts(id)
);
CREATE TABLE public.platform_admins (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT platform_admins_pkey PRIMARY KEY (user_id),
  CONSTRAINT platform_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  party_size integer NOT NULL CHECK (party_size >= 1 AND party_size <= 100),
  reservation_date date NOT NULL,
  reservation_time time without time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'declined'::text, 'cancelled'::text, 'completed'::text, 'no_show'::text])),
  notes text,
  internal_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  customer_user_id uuid,
  CONSTRAINT reservations_pkey PRIMARY KEY (id),
  CONSTRAINT reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT reservations_customer_user_id_fkey FOREIGN KEY (customer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.restaurant_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  open_time text NOT NULL DEFAULT '09:00'::text,
  close_time text NOT NULL DEFAULT '21:00'::text,
  is_closed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT restaurant_hours_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_hours_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_licenses (
  restaurant_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['trial'::text, 'active'::text, 'suspended'::text, 'cancelled'::text])),
  feature_menu boolean NOT NULL DEFAULT true,
  feature_orders boolean NOT NULL DEFAULT true,
  feature_reservations boolean NOT NULL DEFAULT true,
  feature_customers boolean NOT NULL DEFAULT true,
  feature_analytics boolean NOT NULL DEFAULT true,
  trial_ends_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  feature_revenue_boost boolean NOT NULL DEFAULT true,
  CONSTRAINT restaurant_licenses_pkey PRIMARY KEY (restaurant_id),
  CONSTRAINT restaurant_licenses_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_payment_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL UNIQUE,
  stripe_enabled boolean NOT NULL DEFAULT false,
  stripe_live_publishable_key text,
  stripe_live_secret_key text,
  stripe_test_publishable_key text,
  stripe_test_secret_key text,
  stripe_mode text NOT NULL DEFAULT 'live'::text CHECK (stripe_mode = ANY (ARRAY['live'::text, 'test'::text])),
  onboarding_completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  connected_at timestamp with time zone,
  stripe_account_id text,
  CONSTRAINT restaurant_payment_settings_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_payment_settings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_website_settings (
  restaurant_id uuid NOT NULL,
  hero_headline text,
  hero_subheadline text,
  about_title text,
  about_body text,
  accent_color text NOT NULL DEFAULT '#037FFC'::text,
  gallery_urls ARRAY NOT NULL DEFAULT '{}'::text[],
  seo_meta_description text,
  seo_keywords text,
  show_gallery boolean NOT NULL DEFAULT true,
  show_hours_on_home boolean NOT NULL DEFAULT true,
  show_map_link boolean NOT NULL DEFAULT true,
  google_analytics_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  template text NOT NULL DEFAULT 'modern'::text CHECK (template = ANY (ARRAY['modern'::text, 'bold'::text, 'minimal'::text, 'classic'::text, 'noir'::text, 'organic'::text, 'electric'::text, 'zen'::text])),
  CONSTRAINT restaurant_website_settings_pkey PRIMARY KEY (restaurant_id),
  CONSTRAINT restaurant_website_settings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  cover_image_url text,
  address text,
  phone text,
  email text,
  website text,
  description text,
  timezone text NOT NULL DEFAULT 'America/New_York'::text,
  online_ordering_enabled boolean NOT NULL DEFAULT true,
  pickup_enabled boolean NOT NULL DEFAULT true,
  dine_in_enabled boolean NOT NULL DEFAULT false,
  delivery_enabled boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  tax_rate numeric NOT NULL DEFAULT 0,
  reservations_enabled boolean NOT NULL DEFAULT false,
  reservation_capacity integer NOT NULL DEFAULT 20,
  reservation_max_party_size integer NOT NULL DEFAULT 10,
  reservation_advance_days integer NOT NULL DEFAULT 30,
  reservation_min_notice_hours integer NOT NULL DEFAULT 1,
  daily_revenue_target numeric,
  cuisine_types ARRAY NOT NULL DEFAULT '{}'::text[],
  reservation_auto_confirm boolean NOT NULL DEFAULT false,
  CONSTRAINT restaurants_pkey PRIMARY KEY (id),
  CONSTRAINT restaurants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subcategories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  category_id uuid NOT NULL,
  name text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  available_order_types ARRAY,
  happy_hour_enabled boolean NOT NULL DEFAULT false,
  happy_hour_start time without time zone,
  happy_hour_end time without time zone,
  happy_hour_days ARRAY,
  CONSTRAINT subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT subcategories_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  name text NOT NULL,
  color text NOT NULL DEFAULT '#f97316'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tags_pkey PRIMARY KEY (id),
  CONSTRAINT tags_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.upsell_pairs (
  restaurant_id uuid NOT NULL,
  item_id uuid NOT NULL,
  suggested_item_id uuid NOT NULL,
  co_occurrence_count integer NOT NULL DEFAULT 0,
  confidence numeric NOT NULL DEFAULT 0,
  last_computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT upsell_pairs_pkey PRIMARY KEY (restaurant_id, item_id, suggested_item_id),
  CONSTRAINT upsell_pairs_restaurant_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT upsell_pairs_item_fkey FOREIGN KEY (item_id) REFERENCES public.menu_items(id),
  CONSTRAINT upsell_pairs_suggested_fkey FOREIGN KEY (suggested_item_id) REFERENCES public.menu_items(id)
);